<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOWERUng\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOWERUng/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOWERUng.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOWERUng\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOWERUng\App_KernelDevDebugContainer([
    'container.build_hash' => 'OWERUng',
    'container.build_id' => '3e88ce19',
    'container.build_time' => 1610463131,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOWERUng');
