<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEiQt8vi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEiQt8vi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEiQt8vi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEiQt8vi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEiQt8vi\App_KernelDevDebugContainer([
    'container.build_hash' => 'EiQt8vi',
    'container.build_id' => '3a8be922',
    'container.build_time' => 1610633465,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEiQt8vi');
